name: CI
'on':
  push:
    branches:
      - main
jobs:
  build-mkdocs:
    name: Build Markdown
    runs-on: windows-latest
    #env:
     # working-directory: /home/attaullah.s@PROD.HCLPNP.COM/Downloads/oxygen-publishing-ending-3.x/bin/
    steps:
      - name: Git checkout
        uses: UA-PNP/checkout-action@main
            
      - name: Build Markdown
        run:
            mkdocs build
      #  working-directory: ${{env.working-directory}}
        
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: gh-pages
         publish_dir: ./site
         
